"use client";
/* eslint-disable @next/next/no-img-element -- administrator-selected Cloudinary product images */

import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import axios from 'axios';
import { createProduct, deleteProduct, getProducts, updateProduct } from '@/lib/api';
import MediaPicker, { type MediaAsset } from '@/components/media/MediaPicker';

type Localized = { rw: string; en: string; fr: string };
type Product = { _id: string; name: Localized; description: Localized; category: string; image: string; hasPrice: boolean; price?: number; inStock: boolean; featured: boolean };
const empty = { nameRw: '', nameEn: '', nameFr: '', descriptionRw: '', descriptionEn: '', descriptionFr: '', category: 'Poultry equipment', hasPrice: false, price: '', inStock: true, featured: false };

export default function ProductAdminPage() {
  const [products, setProducts] = useState<Product[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [image, setImage] = useState<File | null>(null); const [imageUrl, setImageUrl] = useState(''); const [picker, setPicker] = useState(false); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('');
  const load = () => getProducts().then(({ data }) => setProducts(data)).catch(() => setNotice('Unable to load products. Check the backend deployment.')).finally(() => setLoading(false));
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, []);
  const reset = () => { setForm(empty); setEditing(null); setImage(null); setImageUrl(''); };
  const edit = (product: Product) => { setEditing(product._id); setForm({ nameRw: product.name.rw, nameEn: product.name.en, nameFr: product.name.fr, descriptionRw: product.description.rw, descriptionEn: product.description.en, descriptionFr: product.description.fr, category: product.category, hasPrice: product.hasPrice, price: product.price ? String(product.price) : '', inStock: product.inStock, featured: product.featured }); setImageUrl(product.image); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setNotice(''); const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, String(value))); if (image) data.append('image', image); if (imageUrl) data.append('imageUrl', imageUrl); try { if (editing) await updateProduct(editing, data); else await createProduct(data); setNotice(editing ? 'Product updated successfully.' : 'Product published successfully.'); reset(); await load(); } catch (error: unknown) { setNotice(axios.isAxiosError(error) ? error.response?.data?.message || 'The product could not be saved.' : 'The product could not be saved.'); } finally { setBusy(false); } };
  const remove = async (product: Product) => { if (!confirm(`Delete ${product.name.rw}?`)) return; try { await deleteProduct(product._id); setProducts((current) => current.filter((item) => item._id !== product._id)); } catch { setNotice('The product could not be deleted.'); } };
  const field = (key: keyof typeof form, placeholder: string, textarea = false) => textarea ? <textarea value={String(form[key])} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={placeholder} className="input min-h-28 resize-y" /> : <input value={String(form[key])} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={placeholder} className="input" />;
  return <div className="space-y-8"><header><p className="text-xs font-black uppercase tracking-[.18em] text-leaf">Marketplace publishing</p><h1 className="mt-2 text-3xl font-bold text-forest">Eguriro products</h1><p className="mt-2 text-sm text-slate">Publish equipment, medicines, feeds and other agricultural products with optional pricing.</p></header>
    {notice && <p role="status" className="rounded-2xl border border-leaf/15 bg-white p-4 text-sm font-bold text-forest">{notice}</p>}
    <section className="surface rounded-[2rem] p-5 sm:p-8"><div className="mb-7 flex items-center justify-between"><h2 className="text-lg font-bold text-forest">{editing ? 'Edit product' : 'Add a product'}</h2>{editing && <button onClick={reset} className="secondary-button">Cancel edit</button>}</div><form onSubmit={submit} className="grid gap-7 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-6">
      <fieldset><legend className="field-label">Product names</legend><div className="grid gap-3 md:grid-cols-3">{field('nameRw','Kinyarwanda name')}{field('nameEn','English name')}{field('nameFr','French name')}</div></fieldset>
      <fieldset><legend className="field-label">Descriptions</legend><div className="grid gap-3 md:grid-cols-3">{field('descriptionRw','Kinyarwanda description',true)}{field('descriptionEn','English description',true)}{field('descriptionFr','French description',true)}</div></fieldset>
      <div className="grid gap-4 sm:grid-cols-2"><label><span className="field-label">Category</span><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} className="input"><option>Poultry equipment</option><option>Veterinary medicines</option><option>Feeds and supplements</option><option>Farm machinery</option><option>Livestock supplies</option><option>Other agriculture</option></select></label><label><span className="field-label">Price in RWF</span><input type="number" min="0" disabled={!form.hasPrice} value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder={form.hasPrice ? 'Example: 45000' : 'Enable pricing first'} className="input disabled:opacity-50" /></label></div>
      <div className="flex flex-wrap gap-5">{([['hasPrice','Show a price'],['inStock','Currently available'],['featured','Feature on homepage']] as const).map(([key,label]) => <label key={key} className="flex items-center gap-3 text-sm font-bold text-forest"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => setForm({ ...form, [key]: event.target.checked })} className="h-5 w-5 accent-leaf" />{label}</label>)}</div>
    </div><aside className="space-y-4"><div className="rounded-2xl border-2 border-dashed border-ink/10 bg-mist p-5 text-center"><div className="mx-auto h-48 overflow-hidden rounded-xl bg-white">{(imageUrl || image) ? <img src={image ? URL.createObjectURL(image) : imageUrl} alt="Product preview" className="h-full w-full object-cover" /> : <span className="grid h-full place-items-center text-3xl text-slate/35"><i className="fa-regular fa-image" /></span>}</div><input type="file" accept="image/*" onChange={(event) => setImage(event.target.files?.[0] || null)} className="mt-4 w-full text-xs" /><button type="button" onClick={() => setPicker(true)} className="mt-3 text-xs font-black text-leaf">Choose from media library</button></div><button disabled={busy} className="primary-button min-h-12 w-full">{busy ? 'Saving…' : editing ? 'Update product' : 'Publish product'}</button></aside></form></section>
    <section><div className="mb-5 flex items-center justify-between"><h2 className="font-bold text-forest">Published products</h2><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-leaf">{products.length}</span></div>{loading ? <div className="h-48 animate-pulse rounded-3xl bg-white" /> : <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><AnimatePresence>{products.map((product) => <motion.article key={product._id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="surface overflow-hidden rounded-3xl"><img src={product.image} alt="" className="aspect-[16/10] w-full object-cover" /><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase text-leaf">{product.category}</p><h3 className="mt-1 font-bold text-forest">{product.name.rw}</h3></div><span className={`rounded-full px-2 py-1 text-[9px] font-black ${product.inStock ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-700'}`}>{product.inStock ? 'IN STOCK' : 'OFF'}</span></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate">{product.description.rw}</p><p className="mt-4 text-sm font-black text-forest">{product.hasPrice && product.price ? `${product.price.toLocaleString()} RWF` : 'Price by inquiry'}</p><div className="mt-4 flex gap-2"><button onClick={() => edit(product)} className="secondary-button flex-1"><i className="fa-solid fa-pen" />Edit</button><button onClick={() => remove(product)} className="secondary-button text-red-600"><i className="fa-solid fa-trash" /></button></div></div></motion.article>)}</AnimatePresence></div>}</section>
    <MediaPicker open={picker} onClose={() => setPicker(false)} onSelect={(asset: MediaAsset) => { setImageUrl(asset.url); setImage(null); setPicker(false); }} />
  </div>;
}
