"use client";
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import ContentSkeleton from '@/components/ui/ContentSkeleton';
import { fetchLatestYouTubeVideos } from '@/lib/api';
import { useI18n } from '@/lib/i18n';
import type { YouTubeVideo } from '@/lib/youtube';
import YouTubeVideoCard from '@/components/video/YouTubeVideoCard';
import VideoPlayerModal from '@/components/video/VideoPlayerModal';
export default function VideoGallery(){const{t,locale}=useI18n();const[videos,setVideos]=useState<YouTubeVideo[]>([]);const[selected,setSelected]=useState<YouTubeVideo|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const close=useCallback(()=>setSelected(null),[]);useEffect(()=>{fetchLatestYouTubeVideos(4).then(res=>setVideos(res.data.videos||[])).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);const schema=videos.map((video)=>({"@type":"VideoObject",name:video.title,description:video.description||video.title,thumbnailUrl:[video.thumbnail],uploadDate:video.publishedAt,duration:video.duration,embedUrl:video.embedUrl,contentUrl:video.youtubeUrl}));return <section className="bg-white py-20" aria-labelledby="latest-videos-title"><div className="section-shell"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="mb-2 text-[11px] font-black uppercase tracking-[.2em] text-red-500">{t('videos.latest')}</p><h2 id="latest-videos-title" className="text-3xl font-bold text-isoko-dark sm:text-4xl">{t('videos.title')}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{t('videos.latestBody')}</p></div><Link href="/videos" className="hidden items-center gap-2 text-sm font-bold text-isoko-primary sm:flex">{t('common.viewAll')}<i className="fa-solid fa-arrow-right text-xs"/></Link></div>{loading&&<ContentSkeleton count={4}/>} {!loading&&!error&&videos.length>0&&<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{videos.map((video,index)=><YouTubeVideoCard key={video.id} video={video} index={index} locale={locale==='rw'?'rw-RW':locale==='fr'?'fr-FR':'en-US'} onPlay={setSelected}/>)}</div>}{!loading&&(error||!videos.length)&&<div className="rounded-3xl border border-isoko-dark/8 bg-[#f5faf6] px-6 py-14 text-center"><i className="fa-brands fa-youtube mb-4 text-4xl text-red-500"/><p className="font-bold text-isoko-dark">{t('videos.unavailable')}</p><a href="https://youtube.com/@Isokoyubworozi" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-sm font-extrabold text-red-600">{t('videos.visit')}</a></div>}<Link href="/videos" className="mt-7 flex items-center justify-center gap-2 rounded-xl border border-isoko-dark/10 py-3 text-sm font-bold text-isoko-primary sm:hidden">{t('common.viewAll')}<i className="fa-solid fa-arrow-right text-xs"/></Link></div>{schema.length>0&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@graph":schema})}}/>}<VideoPlayerModal video={selected} onClose={close}/></section>}
