import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
interface Book{_id:string;title:string;description:string;category:string;price:number;coverImage:string;fileUrl?:string;isPremium:boolean;createdAt:string;updatedAt:string}
const api=process.env.NEXT_PUBLIC_API_URL||'http://localhost:5000/api';const site=process.env.NEXT_PUBLIC_SITE_URL||'https://isokoyubworozi.com';
async function getBook(id:string){try{const response=await fetch(`${api}/books/${encodeURIComponent(id)}`,{next:{revalidate:300}});if(!response.ok)return null;return response.json() as Promise<Book>}catch{return null}}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params;const book=await getBook(id);if(!book)return{title:'Book not found'};return{title:book.title,description:book.description.slice(0,160),alternates:{canonical:`/books/${book._id}`},openGraph:{title:book.title,description:book.description,images:[book.coverImage]}}}
export default async function BookPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const book=await getBook(id);if(!book)notFound();const schema={"@context":"https://schema.org","@type":"Book",name:book.title,description:book.description,image:book.coverImage,genre:book.category,url:`${site}/books/${book._id}`,offers:{"@type":"Offer",price:book.price,priceCurrency:'RWF',availability:'https://schema.org/InStock'}};return <main id="main-content"><Navbar/><section className="min-h-[80vh] bg-[#f5faf6] pb-20 pt-32"><div className="section-shell"><Link href="/books" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-isoko-primary"><i className="fa-solid fa-arrow-left text-xs"/>Back to library</Link><div className="grid gap-10 rounded-[2rem] border border-isoko-dark/8 bg-white p-6 shadow-[0_20px_60px_rgba(6,59,31,.08)] md:grid-cols-[280px_1fr] md:p-10"><div className="relative aspect-[3/4] overflow-hidden rounded-2xl bg-isoko-light shadow-lg"><Image fill priority sizes="280px" src={book.coverImage} alt={book.title} className="object-cover"/></div><div className="self-center"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-isoko-light px-3 py-1 text-xs font-extrabold text-isoko-primary">{book.category}</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-extrabold text-amber-800">{book.isPremium?'Premium':'Free'}</span></div><h1 className="mt-5 text-3xl font-bold text-isoko-dark sm:text-4xl">{book.title}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">{book.description}</p><div className="mt-8">{!book.isPremium&&book.fileUrl?<a href={book.fileUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-isoko-accent px-6 py-3.5 text-sm font-extrabold text-white"><i className="fa-solid fa-book-open"/>Read free book</a>:book.isPremium?<Link href="/account?next=/books" className="inline-flex items-center gap-2 rounded-xl bg-isoko-dark px-6 py-3.5 text-sm font-extrabold text-white"><i className="fa-solid fa-lock"/>{book.price.toLocaleString()} RWF — unlock with account</Link>:<span className="text-sm font-bold text-slate-400">File coming soon</span>}</div></div></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Footer/></main>}
