"use client";
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { FiArrowRight, FiEye, FiEyeOff, FiLock, FiMail, FiUser } from 'react-icons/fi';
import { adminLogin, registerAdmin } from '@/lib/api';
export default function AdminAccessForm() {
  const router = useRouter(); const [mode,setMode]=useState<'login'|'setup'>('login'); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState({name:'',email:'',password:'',setupKey:''});
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const result=mode==='login'?await adminLogin({email:form.email,password:form.password}):await registerAdmin({name:form.name,email:form.email,password:form.password},form.setupKey);sessionStorage.setItem('admin_token',result.data.token);sessionStorage.setItem('admin_user',JSON.stringify(result.data));router.replace('/admin');}catch(requestError:unknown){const err=requestError as {response?:{data?:{message?:string}}};setError(err.response?.data?.message||'We could not complete this request. Check the details and try again.');}finally{setBusy(false)}};
  const input='w-full rounded-2xl border border-ink/10 bg-mist/70 px-11 py-3.5 text-sm outline-none transition focus:border-leaf focus:ring-4 focus:ring-leaf/10';
  return <div><div className="mb-7 flex rounded-xl bg-mist p-1" role="tablist" aria-label="Administrator access mode">{(['login','setup'] as const).map(item=><button key={item} type="button" onClick={()=>{setMode(item);setError('')}} className={`flex-1 rounded-lg px-3 py-2 text-xs font-bold transition ${mode===item?'bg-white text-forest shadow-sm':'text-slate'}`}>{item==='login'?'Sign in':'First admin setup'}</button>)}</div><form onSubmit={submit} className="space-y-4">
    {mode==='setup'&&<label className="relative block"><span className="field-label">Full name</span><FiUser className="field-icon"/><input className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="Editorial administrator"/></label>}
    <label className="relative block"><span className="field-label">Email address</span><FiMail className="field-icon"/><input className={input} type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required placeholder="admin@isokoyubworozi.rw"/></label>
    <label className="relative block"><span className="field-label">Password</span><FiLock className="field-icon"/><input className={input} type={show?'text':'password'} minLength={mode==='setup'?10:1} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required placeholder="Your secure password"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)} className="absolute bottom-3.5 right-4 text-slate">{show?<FiEyeOff/>:<FiEye/>}</button></label>
    {mode==='setup'&&<label className="relative block"><span className="field-label">One-time setup key</span><FiLock className="field-icon"/><input className={input} type="password" value={form.setupKey} onChange={e=>setForm({...form,setupKey:e.target.value})} required placeholder="From the backend environment"/><p className="mt-2 text-xs leading-5 text-slate">The API checks this key. It is never saved in the browser.</p></label>}
    {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="primary-button w-full">{busy?'Please wait…':mode==='login'?'Enter command centre':'Create administrator'}<FiArrowRight/></button>
  </form></div>;
}
