import axios from 'axios';
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';
const API = axios.create({ baseURL: API_URL, timeout: 20000 });
API.interceptors.request.use((config) => { const token = typeof window !== 'undefined' ? sessionStorage.getItem('admin_token') : null; if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
API.interceptors.response.use((response) => response, (error) => { if ([401, 403].includes(error.response?.status) && typeof window !== 'undefined') { sessionStorage.removeItem('admin_token'); sessionStorage.removeItem('admin_user'); if (window.location.pathname.startsWith('/admin')) window.location.assign('/login'); } return Promise.reject(error); });
export const getBooks = () => API.get('/books/admin/all');
export const uploadBook = (data: FormData) => API.post('/books', data);
export const updateBook = (id: string, data: FormData) => API.put(`/books/${id}`, data);
export const deleteBook = (id: string) => API.delete(`/books/${id}`);
export const getArticles = () => API.get('/articles');
export const uploadArticle = (data: FormData) => API.post('/articles', data);
export const updateArticle = (id: string, data: FormData) => API.put(`/articles/${id}`, data);
export const deleteArticle = (id: string) => API.delete(`/articles/${id}`);
export const getVideos = () => API.get('/videos');
export const uploadVideo = (data: { title: string; youtubeUrl: string; category: string }) => API.post('/videos', data);
export const updateVideo = (id: string, data: { title: string; youtubeUrl: string; category: string }) => API.put(`/videos/${id}`, data);
export const deleteVideo = (id: string) => API.delete(`/videos/${id}`);
export const getStats = () => API.get('/stats');
export const getRecentActivity = () => API.get('/stats/recent');
export const getMedia = () => API.get('/media');
export const adminLogin = (data: { email: string; password: string }) => API.post('/auth/admin/login', data);
export const registerAdmin = (data: { name: string; email: string; password: string }, setupKey: string) => API.post('/auth/admin/register', data, { headers: { 'x-admin-setup-key': setupKey } });
export const getAdminMe = () => API.get('/auth/admin/me');
export default API;
