"use client";

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { fetchCart, removeCartProduct, updateCartProduct } from '@/lib/api';
import { getSession, type Session } from '@/lib/session';
import { localized, whatsappUrl, type CartItem } from '@/lib/marketplace';
import { useI18n } from '@/lib/i18n';

const copy = { en: { title: 'Your inquiry cart', body: 'Review the products below, then send the complete list to our WhatsApp team. Online payment will be added later.', empty: 'Your cart is empty.', shop: 'Explore marketplace', send: 'Send inquiry on WhatsApp', sign: 'Sign in to use your marketplace cart', remove: 'Remove', total: 'Priced subtotal', request: 'Products requiring a price quote' }, rw: { title: 'Agatebo k’ubusabe', body: 'Banza urebe ibicuruzwa wahisemo, ubone kubyohereza ku ikipe yacu ya WhatsApp. Kwishyura kuri interineti bizongerwaho nyuma.', empty: 'Agatebo kawe karimo ubusa.', shop: 'Sura Eguriro', send: 'Ohereza ubusabe kuri WhatsApp', sign: 'Injira kugira ngo ukoreshe agatebo k’Eguriro', remove: 'Kuramo', total: 'Igiteranyo cy’ibifite igiciro', request: 'Ibicuruzwa bisaba kubarizwa igiciro' }, fr: { title: 'Votre panier de demande', body: 'Vérifiez les produits, puis envoyez la liste à notre équipe WhatsApp. Le paiement en ligne sera ajouté ultérieurement.', empty: 'Votre panier est vide.', shop: 'Explorer le marché', send: 'Envoyer sur WhatsApp', sign: 'Connectez-vous pour utiliser le panier', remove: 'Retirer', total: 'Sous-total tarifé', request: 'Produits avec prix sur demande' } };

export default function CartPage() {
  const { locale } = useI18n(); const words = copy[locale]; const [items, setItems] = useState<CartItem[]>([]); const [loading, setLoading] = useState(true); const [session, setSession] = useState<Session | null>(null); const [ready, setReady] = useState(false);
  const load = () => fetchCart().then(({ data }) => setItems(data)).finally(() => setLoading(false));
  useEffect(() => { const frame = requestAnimationFrame(() => { const current = getSession(); setSession(current); setReady(true); if (current) load(); else setLoading(false); }); return () => cancelAnimationFrame(frame); }, []);
  const quantity = async (item: CartItem, value: number) => { setItems((current) => current.map((entry) => entry.product._id === item.product._id ? { ...entry, quantity: value } : entry)); await updateCartProduct(item.product._id, value); window.dispatchEvent(new Event('isoko-cart-change')); };
  const remove = async (id: string) => { await removeCartProduct(id); setItems((current) => current.filter((entry) => entry.product._id !== id)); window.dispatchEvent(new Event('isoko-cart-change')); };
  const subtotal = items.reduce((sum, item) => sum + (item.product.hasPrice && item.product.price ? item.product.price * item.quantity : 0), 0); const quotes = items.filter((item) => !item.product.hasPrice).length;
  const message = `Hello Isoko y’Ubworozi, I would like to inquire about these marketplace items:\n\n${items.map((item, index) => `${index + 1}. ${localized(item.product.name, locale)} × ${item.quantity}${item.product.hasPrice && item.product.price ? ` — ${(item.product.price * item.quantity).toLocaleString()} RWF` : ' — price request'}`).join('\n')}\n\nAccount: ${session?.name || ''} (${session?.email || ''})\nPlease confirm availability, final price and delivery options.`;
  return <main id="main-content"><Navbar /><section className="min-h-screen bg-[#f4f8f5] pb-20 pt-32"><div className="mx-auto w-[min(100%-2.5rem,68rem)]"><p className="text-xs font-black uppercase tracking-[.18em] text-isoko-accent">Eguriro</p><h1 className="mt-2 text-3xl font-bold text-isoko-dark sm:text-4xl">{words.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{words.body}</p>
    {!ready || loading ? <div className="mt-8 h-52 animate-pulse rounded-3xl bg-white" /> : !session ? <div className="mt-8 rounded-3xl bg-white p-10 text-center shadow-sm"><i className="fa-solid fa-user-lock text-3xl text-isoko-accent" /><p className="mt-4 font-bold text-isoko-dark">{words.sign}</p><Link href="/account?next=/cart" className="mt-5 inline-flex rounded-xl bg-isoko-dark px-6 py-3 text-sm font-extrabold text-white">Sign in</Link></div> : !items.length ? <div className="mt-8 rounded-3xl border border-dashed border-isoko-dark/15 bg-white p-12 text-center"><i className="fa-solid fa-basket-shopping text-3xl text-isoko-accent" /><p className="mt-4 font-bold text-slate-500">{words.empty}</p><Link href="/eguriro" className="mt-5 inline-flex text-sm font-extrabold text-isoko-primary">{words.shop}</Link></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_22rem]"><div className="space-y-4">{items.map((item) => <article key={item.product._id} className="flex gap-4 rounded-2xl border border-isoko-dark/8 bg-white p-4 sm:items-center"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-isoko-light"><Image fill sizes="96px" src={item.product.image} alt="" className="object-cover" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase text-isoko-accent">{item.product.category}</p><h2 className="mt-1 font-bold text-isoko-dark">{localized(item.product.name, locale)}</h2><p className="mt-2 text-xs font-black text-isoko-primary">{item.product.hasPrice && item.product.price ? `${item.product.price.toLocaleString()} RWF` : words.request}</p><div className="mt-3 flex items-center gap-3"><label className="sr-only">Quantity</label><select value={item.quantity} onChange={(event) => quantity(item, Number(event.target.value))} className="rounded-lg border border-isoko-dark/10 px-3 py-2 text-xs font-bold">{[1,2,3,4,5,6,7,8,9,10].map((value) => <option key={value}>{value}</option>)}</select><button onClick={() => remove(item.product._id)} className="text-xs font-bold text-red-600"><i className="fa-solid fa-trash mr-1" />{words.remove}</button></div></div></article>)}</div><aside className="h-fit rounded-3xl bg-isoko-dark p-6 text-white"><p className="text-xs font-black uppercase tracking-wider text-isoko-light">{words.total}</p><p className="mt-2 text-2xl font-black">{subtotal.toLocaleString()} RWF</p>{quotes > 0 && <p className="mt-3 text-xs text-white/65">{quotes} {words.request.toLowerCase()}</p>}<a href={whatsappUrl(message)} target="_blank" rel="noopener noreferrer" className="mt-6 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#25D366] px-5 text-center text-sm font-extrabold text-white"><i className="fa-brands fa-whatsapp text-lg" />{words.send}</a><p className="mt-4 text-[11px] leading-5 text-white/55">No payment is collected on this page. Our team confirms every order personally.</p></aside></div>}
    </div></section><Footer /></main>;
}
