"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Locale = "rw" | "en" | "fr";

const en = {
  "nav.home":"Home","nav.videos":"Videos","nav.blog":"Articles","nav.library":"Library","nav.about":"About","nav.contact":"Contact","nav.account":"Account","nav.subscribe":"Subscribe","nav.open":"Open menu","nav.close":"Close menu","language.choose":"Choose language",
  "hero.eyebrow":"Practical poultry knowledge for East Africa","hero.title":"Healthier chickens.","hero.titleAccent":"More profitable farms.","hero.body":"Learn proven poultry care, disease prevention, vaccination, feeding and farm management in clear language you can apply immediately.","hero.watch":"Watch lessons","hero.read":"Read articles","hero.videos":"Practical lessons","hero.farmers":"Farmers reached","hero.new":"Fresh guidance",
  "common.explore":"Explore","common.viewAll":"View all","common.all":"All","common.loading":"Loading content","common.free":"Free","common.comingSoon":"Coming soon",
  "guidance.eyebrow":"Choose how you learn","guidance.title":"Useful knowledge for every stage of your farm","guidance.videoTitle":"Field video lessons","guidance.videoBody":"Follow practical demonstrations on housing, feeding, vaccination and daily care.","guidance.articleTitle":"Expert explanations","guidance.articleBody":"Understand diseases, markets, seasonal risks and productive decisions.","guidance.bookTitle":"Digital farming library","guidance.bookBody":"Read free guides or securely unlock premium books prepared for farm growth.",
  "library.eyebrow":"Digital farming library","library.title":"Practical books for better farming","library.body":"Find structured guides on poultry health, feeding, housing, production and profitable farm management.","library.download":"Read free","library.soon":"File coming soon","library.empty":"No books are available yet. Please check again soon.","library.premium":"Premium","library.noCategory":"No books were found in this category.","library.howEyebrow":"How access works","library.howTitle":"Start free. Unlock more when you need it.","library.howBody":"Every book is clearly marked so you know whether it is free or requires payment.","library.freeTitle":"Free books","library.freeBody":"Open books uploaded for farmers by the Isoko y'Ubworozi team without payment.","library.premiumTitle":"Premium books","library.premiumBody":"Pay through an approved method. After verification, access is added to your account.","library.accountTitle":"Your learning account","library.accountBody":"Keep verified purchases, entitled resources and future learning activity in one secure place.","library.createAccount":"Create an account",
  "videos.eyebrow":"Watch and apply","videos.title":"Poultry lessons from the field","videos.body":"Watch practical demonstrations on any device and apply each lesson on your farm.","videos.empty":"No videos are available yet.","videos.noCategory":"No videos were found in this category.","videos.visit":"Visit our YouTube channel",
  "blog.eyebrow":"Farming explained clearly","blog.title":"Guidance for better farm decisions","blog.body":"Read straightforward advice about animal health, planning, costs and productive poultry management.","blog.read":"Read article","blog.back":"Back to articles","blog.empty":"No articles are available yet.","blog.noCategory":"No articles were found in this category.","blog.by":"By",
  "story.eyebrow":"Built for East African farmers","story.title":"Veterinary science made practical.","story.body":"Isoko y'Ubworozi connects expert animal-health knowledge with daily decisions that make farms productive, sustainable and profitable.","story.health":"Disease prevention","story.feed":"Low-cost feeding","story.business":"Farm profitability",
  "market.eyebrow":"The next step","market.title":"Trusted poultry supplies, closer to your farm.","market.body":"We are preparing a secure marketplace where farmers can discover verified poultry medicines and health supplies, understand their correct use and order online.","market.badge":"Medicine marketplace coming soon","market.verify":"Verified products","market.guidance":"Clear usage guidance","market.secure":"Secure account checkout",
  "cta.title":"See every lesson in action.","cta.body":"Follow field demonstrations, vaccination guidance and practical poultry masterclasses on our YouTube channel.","cta.visit":"Visit YouTube",
  "about.eyebrow":"About Isoko y'Ubworozi","about.title":"Knowledge that turns livestock care into sustainable business.","about.body":"We translate veterinary science into practical steps for farmers, entrepreneurs and rural youth across East Africa.","about.missionEyebrow":"Our mission","about.missionTitle":"Make reliable farming knowledge understandable and useful.","about.missionBody1":"We bridge expert veterinary science and the real decisions farmers make daily, from poultry production and disease prevention to vaccination, low-cost feed and financial risk.","about.missionBody2":"Kinyarwanda-first teaching, supported by English and French, lets farmers learn at their pace and confidently apply modern techniques.","about.statLessons":"Practical lessons","about.statFarmers":"Farmers reached","about.statLanguages":"Supported languages","about.statUpdates":"New guidance","about.valuesEyebrow":"What guides us","about.valuesTitle":"Built around farmers' real needs","about.valueEducation":"Accessible education","about.valueEducationBody":"Clear instruction in languages farmers understand.","about.valueEvidence":"Practical evidence","about.valueEvidenceBody":"Field guidance grounded in animal-health practice.","about.valueSustainability":"Sustainable growth","about.valueSustainabilityBody":"Lower costs, healthier animals and stronger businesses.","about.ctaTitle":"Ready to improve your farm?","about.ctaBody":"Begin with a free lesson or explore the farming library.","about.ctaVideo":"Watch lessons","about.ctaLibrary":"Explore library",
  "faq.eyebrow":"Frequently asked questions","faq.title":"Understand the platform before you begin","faq.q1":"What can I learn here?","faq.a1":"Learn poultry setup, housing, feeding, disease prevention, vaccination, farm finance and livestock management through videos, articles and books.","faq.q2":"How do free books work?","faq.a2":"Books marked Free open without payment. They are uploaded by the administration for farmers to read and use.","faq.q3":"How do I access a premium book?","faq.a3":"Pay through an approved method. After verification, access is linked to your account so you can return to the resource.","faq.q4":"Why should I create an account?","faq.a4":"Your account keeps verified purchases, protects premium access and will support learning and order tracking.","faq.q5":"Can I buy poultry medicine now?","faq.a5":"Not yet. A verified medicine marketplace is being prepared and the website will announce when ordering opens.",
  "contact.eyebrow":"Contact the team","contact.title":"Ask, collaborate or request guidance","contact.body":"Contact us about farming education, resources, partnerships or technical support.","contact.reach":"Contact information","contact.location":"Location","contact.follow":"Follow Isoko y'Ubworozi","contact.formTitle":"Send a message","contact.formBody":"Complete the form and our team will respond as soon as possible.","contact.name":"Full name","contact.namePlaceholder":"Enter your full name","contact.email":"Email address","contact.subject":"Subject","contact.subjectPlaceholder":"What do you need help with?","contact.message":"Message","contact.messagePlaceholder":"Explain your question or request","contact.send":"Send message","contact.sent":"Your message has been received. We will respond soon.",
  "account.eyebrow":"Your Isoko account","account.title":"Keep learning and purchases in one secure place.","account.body":"Register or sign in to prepare for premium access, payment verification and future order tracking.","account.login":"Sign in","account.register":"Create account","account.name":"Full name","account.email":"Email address","account.password":"Password","account.submitLogin":"Sign in securely","account.submitRegister":"Create my account","account.loading":"Please wait…","account.success":"You are signed in successfully.","account.logout":"Sign out","account.member":"Account ready","account.future":"Premium purchases and medicine orders will appear here when those services launch.","account.error":"We could not complete that request. Check your information and try again.","account.switchRegister":"New here? Create an account","account.switchLogin":"Already registered? Sign in",
  "privacy.eyebrow":"Your information","privacy.title":"Privacy policy","privacy.intro":"This policy explains what information we may collect, why it is used and your choices.","privacy.updated":"Last updated: 9 September 2026","privacy.s1":"Information we collect","privacy.p1":"Account services may collect your name, email and information needed to confirm access to paid resources. Technical data may protect and improve the service.","privacy.s2":"How information is used","privacy.p2":"We use information to provide accounts, verify entitled content, respond to support, improve the platform and prevent misuse. We do not sell personal information.","privacy.s3":"Payments and security","privacy.p3":"Payment providers process payment details under their own terms. We retain only references necessary to verify access and support transactions.","privacy.s4":"Your choices","privacy.p4":"You may request access, correction or deletion of eligible information. Some transaction records may be retained for legal or accounting needs.","privacy.s5":"Contact","privacy.p5":"For privacy questions, contact info@isokoyubworozi.rw.",
  "terms.eyebrow":"Platform rules","terms.title":"Terms of use","terms.intro":"These terms explain responsible use of our lessons, accounts and digital resources.","terms.updated":"Last updated: 9 September 2026","terms.s1":"Educational purpose","terms.p1":"Our content is general agricultural education and does not replace diagnosis or treatment by a qualified veterinary professional.","terms.s2":"Accounts","terms.p2":"Provide accurate information and protect your credentials. Do not share paid access or misuse another person's account.","terms.s3":"Free and premium resources","terms.p3":"Free resources require no payment. Premium resources require successful payment and verification; price and access conditions should appear before payment.","terms.s4":"Content use","terms.p4":"Platform books, videos, articles and branding remain protected. Personal learning is allowed; unauthorized resale or redistribution is not.","terms.s5":"Changes and support","terms.p5":"Features may change or be discontinued. Material term changes will be published here. Contact us for clarification.",
  "footer.body":"Helping farmers build healthier, productive poultry businesses with practical knowledge in languages they understand.","footer.links":"Quick links","footer.resources":"Resources","footer.updates":"Stay informed","footer.updateBody":"Receive farming updates.","footer.email":"Email address","footer.rights":"All rights reserved.","footer.privacy":"Privacy","footer.terms":"Terms","footer.vet":"Veterinary guidance","footer.vaccine":"Vaccination plans","footer.feed":"Feed efficiency","footer.finance":"Farm finance","footer.payments":"Planned payment methods","footer.paymentBody":"These familiar options will support premium resources when payments launch.","footer.paymentSecure":"Secure processing will be enabled at launch."
} as const;

type Key = keyof typeof en;
const rw: Record<Key,string> = {
  ...en,
  "nav.home":"Ahabanza","nav.videos":"Amashusho","nav.blog":"Inyandiko","nav.library":"Isomero","nav.about":"Ibyacu","nav.contact":"Twandikire","nav.account":"Konti","nav.subscribe":"Iyandikishe","nav.open":"Fungura menu","nav.close":"Funga menu","language.choose":"Hitamo ururimi",
  "hero.eyebrow":"Ubumenyi ngiro bw'ubworozi muri Afurika y'Iburasirazuba","hero.title":"Inkoko nzima.","hero.titleAccent":"Ubworozi bwunguka.","hero.body":"Iga kwita ku nkoko, kuzirinda indwara, kuzikingira, kuzigaburira no gucunga ubworozi mu buryo bwumvikana.","hero.watch":"Reba amasomo","hero.read":"Soma inyandiko","hero.videos":"Amasomo ngiro","hero.farmers":"Aborozi twagezeho","hero.new":"Inama nshya",
  "common.explore":"Sura","common.viewAll":"Reba byose","common.all":"Byose","common.loading":"Tegereza gato","common.free":"Ubuntu","common.comingSoon":"Biraza vuba",
  "guidance.eyebrow":"Hitamo uburyo bwo kwiga","guidance.title":"Ubumenyi bugufasha kuri buri ntambwe y'ubworozi","guidance.videoTitle":"Amasomo ngiro ya videwo","guidance.videoBody":"Kurikira uko amazu ategurwa, inkoko zigaburirwa, zikingirwa kandi zitabwaho.","guidance.articleTitle":"Ibisobanuro by'inzobere","guidance.articleBody":"Sobanukirwa indwara, amasoko, ibihe n'ibyemezo biteza ubworozi imbere.","guidance.bookTitle":"Isomero ry'ubworozi","guidance.bookBody":"Soma ibitabo by'ubuntu cyangwa ubone ibihambaye wishyuye mu buryo bwizewe.",
  "library.eyebrow":"Isomero ry'ubworozi","library.title":"Ibitabo ngiro biteza ubworozi imbere","library.body":"Shaka amabwiriza ku buzima bw'inkoko, imirire, amazu, umusaruro n'imicungire ibyara inyungu.","library.download":"Soma ku buntu","library.soon":"Dosiye iraza vuba","library.empty":"Nta bitabo birashyirwaho. Ongera ugaruke vuba.","library.premium":"Icyishyurwa","library.noCategory":"Nta bitabo byabonetse muri iki cyiciro.","library.howEyebrow":"Uko isomero rikoreshwa","library.howTitle":"Tangira ku buntu, ubone ibindi igihe ubikeneye.","library.howBody":"Buri gitabo kigaragaza niba ari ubuntu cyangwa kigomba kwishyurwa.","library.freeTitle":"Ibitabo by'ubuntu","library.freeBody":"Soma ibitabo byashyizweho n'itsinda rya Isoko y'Ubworozi utishyuye.","library.premiumTitle":"Ibitabo byishyurwa","library.premiumBody":"Ishyura mu buryo bwemewe; ubwishyu nibugenzurwa, igitabo gishyirwa kuri konti yawe.","library.accountTitle":"Konti yawe yo kwiga","library.accountBody":"Bika ibyo wishyuye, ibitabo wemerewe n'amakuru y'urugendo rwawe rwo kwiga.","library.createAccount":"Fungura konti",
  "videos.eyebrow":"Reba ubishyire mu bikorwa","videos.title":"Amasomo y'ubworozi ava mu murima","videos.body":"Reba amasomo ngiro ku gikoresho icyo ari cyo cyose maze uyakoreshe mu bworozi bwawe.","videos.empty":"Nta mashusho arashyirwaho.","videos.noCategory":"Nta mashusho yabonetse muri iki cyiciro.","videos.visit":"Sura umuyoboro wacu wa YouTube",
  "blog.eyebrow":"Ubworozi busobanuwe neza","blog.title":"Inama zigufasha gufata ibyemezo byiza","blog.body":"Soma inama ku buzima bw'amatungo, igenamigambi, ibiciro n'imicungire y'inkoko.","blog.read":"Soma inyandiko","blog.back":"Subira ku nyandiko","blog.empty":"Nta nyandiko zirashyirwaho.","blog.noCategory":"Nta nyandiko zabonetse muri iki cyiciro.","blog.by":"Yanditswe na",
  "story.eyebrow":"Byagenewe aborozi bo muri Afurika y'Iburasirazuba","story.title":"Ubumenyi bw'amatungo bushyizwe mu bikorwa.","story.body":"Duhuza ubumenyi bw'inzobere n'ibyemezo bituma ubworozi butanga umusaruro kandi bwunguka.","story.health":"Kurinda indwara","story.feed":"Ibiryo bihendutse","story.business":"Inyungu y'ubworozi",
  "market.eyebrow":"Intambwe ikurikira","market.title":"Ibikoresho byizewe by'inkoko hafi y'umworozi.","market.body":"Turategura isoko aho aborozi bazabona imiti n'ibikoresho byagenzuwe, bakamenya uko bikoreshwa kandi bakabigura kuri interineti.","market.badge":"Isoko ry'imiti riraza vuba","market.verify":"Ibicuruzwa byagenzuwe","market.guidance":"Amabwiriza asobanutse","market.secure":"Kwishyura ukoresheje konti",
  "cta.title":"Reba uko buri somo rikorwa.","cta.body":"Kurikira imyitozo, gahunda z'inkingo n'amasomo ngiro ku muyoboro wacu wa YouTube.","cta.visit":"Jya kuri YouTube",
  "about.eyebrow":"Ibyerekeye Isoko y'Ubworozi","about.title":"Ubumenyi buhindura kwita ku matungo ubucuruzi burambye.","about.body":"Dushyira ubumenyi bw'amatungo mu ntambwe zoroshye zifasha aborozi, ba rwiyemezamirimo n'urubyiruko.","about.missionEyebrow":"Intego yacu","about.missionTitle":"Gutanga ubumenyi bwizewe, bwumvikana kandi bukoreshwa.","about.missionBody1":"Duhuza ubumenyi bw'abaganga b'amatungo n'ibyemezo bya buri munsi: umusaruro, indwara, inkingo, ibiryo bihendutse n'imari.","about.missionBody2":"Twigisha mbere mu Kinyarwanda, tugashyigikirwa n'Icyongereza n'Igifaransa kugira ngo buri mworozi yige neza.","about.statLessons":"Amasomo ngiro","about.statFarmers":"Aborozi twagezeho","about.statLanguages":"Indimi zikoreshwa","about.statUpdates":"Inama nshya","about.valuesEyebrow":"Ibituyobora","about.valuesTitle":"Byubakiye ku byo aborozi bakeneye","about.valueEducation":"Uburezi bugera kuri bose","about.valueEducationBody":"Amabwiriza yumvikana mu ndimi aborozi bumva.","about.valueEvidence":"Ubumenyi ngiro","about.valueEvidenceBody":"Imyitozo n'inama zishingiye ku buzima bw'amatungo.","about.valueSustainability":"Iterambere rirambye","about.valueSustainabilityBody":"Ikiguzi gito, amatungo mazima n'ubucuruzi buramba.","about.ctaTitle":"Witeguye guteza ubworozi imbere?","about.ctaBody":"Tangira isomo ry'ubuntu cyangwa usure isomero.","about.ctaVideo":"Reba amasomo","about.ctaLibrary":"Sura isomero",
  "faq.eyebrow":"Ibibazo bikunze kubazwa","faq.title":"Sobanukirwa urubuga mbere yo gutangira","faq.q1":"Ni iki nakwigira hano?","faq.a1":"Wakwiga gutangira ubworozi, amazu, kugaburira, indwara, inkingo, imari n'imicungire ukoresheje videwo, inyandiko n'ibitabo.","faq.q2":"Ibitabo by'ubuntu bikoreshwa bite?","faq.a2":"Igitabo cyanditseho Ubuntu gifungurwa utishyuye. Gishyirwaho n'ubuyobozi kugira ngo aborozi bagisome.","faq.q3":"Nzabona nte igitabo cyishyurwa?","faq.a3":"Ishyura mu buryo bwemewe. Ubwishyu nibugenzurwa, uburenganzira buhuzwa na konti yawe.","faq.q4":"Kuki nafunguza konti?","faq.a4":"Konti ibika ibyo wishyuye, ikarinda ibitabo wemerewe kandi izafasha gukurikirana ibyo wize n'ibyo watumije.","faq.q5":"Nshobora kugura imiti ubu?","faq.a5":"Oya. Isoko ry'imiti yagenzuwe rirategurwa kandi urubuga ruzatangaza igihe rizafungurwa.",
  "contact.eyebrow":"Vugana n'itsinda","contact.title":"Baza, dukorane cyangwa usabe ubufasha","contact.body":"Twandikire ku burezi bw'ubworozi, ibikoresho, ubufatanye cyangwa ubufasha bwa tekiniki.","contact.reach":"Aho watubariza","contact.location":"Aho duherereye","contact.follow":"Kurikira Isoko y'Ubworozi","contact.formTitle":"Ohereza ubutumwa","contact.formBody":"Uzuza iyi fomu, itsinda ryacu riragusubiza vuba.","contact.name":"Amazina yose","contact.namePlaceholder":"Andika amazina yawe","contact.email":"Imeyili","contact.subject":"Impamvu","contact.subjectPlaceholder":"Ni iki ushaka ko tugufashamo?","contact.message":"Ubutumwa","contact.messagePlaceholder":"Sobanura ikibazo cyangwa icyifuzo","contact.send":"Ohereza ubutumwa","contact.sent":"Ubutumwa bwawe bwakiriwe. Turagusubiza vuba.",
  "account.eyebrow":"Konti ya Isoko","account.title":"Bika amasomo n'ibyo waguze ahantu hizewe.","account.body":"Iyandikishe cyangwa injira kugira ngo ubone ibitabo byishyurwa kandi ukurikirane ibyo uzatumiza.","account.login":"Injira","account.register":"Fungura konti","account.name":"Amazina yose","account.email":"Imeyili","account.password":"Ijambo ry'ibanga","account.submitLogin":"Injira mu buryo bwizewe","account.submitRegister":"Fungura konti yanjye","account.loading":"Tegereza…","account.success":"Winjiye neza kuri konti yawe.","account.logout":"Sohoka","account.member":"Konti iriteguye","account.future":"Ibitabo wishyuye n'imiti watumije bizagaragara hano igihe serivisi zizatangira.","account.error":"Ntitwashoboye kubikora. Suzuma amakuru wongere ugerageze.","account.switchRegister":"Nta konti ufite? Fungura konti","account.switchLogin":"Usanzwe ufite konti? Injira",
  "privacy.eyebrow":"Amakuru yawe","privacy.title":"Politiki y'amabanga","privacy.intro":"Iyi politiki isobanura amakuru dushobora kwakira, impamvu akoreshwa n'uburenganzira bwawe.","privacy.updated":"Yavuguruwe ku wa 9 Nzeri 2026","privacy.s1":"Amakuru twakira","privacy.p1":"Konti ishobora kwakira amazina, imeyili n'amakuru yo kwemeza ibikoresho byishyurwa. Amakuru ya tekiniki ashobora kurinda no kunoza serivisi.","privacy.s2":"Uko amakuru akoreshwa","privacy.p2":"Akoreshwa mu gutanga konti, kugenzura uburenganzira, kugusubiza, kunoza urubuga no kurinda imikoreshereze mibi. Ntiducuruza amakuru bwite.","privacy.s3":"Ubwishyu n'umutekano","privacy.p3":"Abatanga serivisi zo kwishyura ni bo bagenzura amakuru y'ubwishyu. Tubika gusa ibikenewe mu kwemeza no gufasha ku bwishyu.","privacy.s4":"Uburenganzira bwawe","privacy.p4":"Ushobora gusaba kureba, gukosora cyangwa gusiba amakuru yemerewe. Amwe ashobora kubikwa kubera amategeko cyangwa ibaruramari.","privacy.s5":"Twandikire","privacy.p5":"Ku kibazo cy'amabanga, twandikire kuri info@isokoyubworozi.rw.",
  "terms.eyebrow":"Amategeko y'urubuga","terms.title":"Amabwiriza y'imikoreshereze","terms.intro":"Aya mabwiriza asobanura imikoreshereze iboneye y'amasomo, konti n'ibikoresho.","terms.updated":"Yavuguruwe ku wa 9 Nzeri 2026","terms.s1":"Intego y'uburezi","terms.p1":"Ibyo dutangaza ni ubumenyi rusange kandi ntibisimbura isuzuma cyangwa ubuvuzi bw'umuganga w'amatungo.","terms.s2":"Konti","terms.p2":"Tanga amakuru y'ukuri kandi urinde ibanga rya konti. Ntugasangize abandi ibyo wishyuye.","terms.s3":"Ibikoresho by'ubuntu n'ibyishyurwa","terms.p3":"Iby'ubuntu ntibisaba kwishyura. Ibyishyurwa bisaba ubwishyu bwemejwe; igiciro n'amabwiriza bigaragazwa mbere.","terms.s4":"Imikoreshereze y'ibikubiye ku rubuga","terms.p4":"Ibitabo, videwo, inyandiko n'ikirango birarinzwe. Kwiga biremewe; kongera kubigurisha cyangwa kubikwirakwiza nta ruhushya birabujijwe.","terms.s5":"Impinduka n'ubufasha","terms.p5":"Serivisi zishobora guhinduka cyangwa guhagarikwa. Impinduka zikomeye zizatangazwa hano. Twandikire ku bisobanuro.",
  "footer.body":"Dufasha aborozi kugira inkoko nzima n'ubworozi butanga umusaruro mu ndimi bumva.","footer.links":"Aho wakanda","footer.resources":"Ubumenyi","footer.updates":"Menya amakuru","footer.updateBody":"Jya ubona inama.","footer.email":"Imeyili yawe","footer.rights":"Uburenganzira bwose burabitswe.","footer.privacy":"Amabanga","footer.terms":"Amategeko","footer.vet":"Inama z'abaganga b'amatungo","footer.vaccine":"Gahunda z'inkingo","footer.feed":"Imikoreshereze myiza y'ibiryo","footer.finance":"Imari y'ubworozi","footer.payments":"Uburyo bwo kwishyura buteganyijwe","footer.paymentBody":"Ubu buryo buzakoreshwa ku bitabo byishyurwa igihe serivisi izatangira.","footer.paymentSecure":"Kwishyura mu mutekano bizatangirana na serivisi."
};

const fr: Record<Key,string> = {
  ...en,
  "nav.home":"Accueil","nav.videos":"Vidéos","nav.blog":"Articles","nav.library":"Bibliothèque","nav.about":"À propos","nav.contact":"Contact","nav.account":"Compte","nav.subscribe":"S'abonner","nav.open":"Ouvrir le menu","nav.close":"Fermer le menu","language.choose":"Choisir la langue",
  "hero.eyebrow":"Savoir avicole pratique pour l'Afrique de l'Est","hero.title":"Des volailles saines.","hero.titleAccent":"Des fermes plus rentables.","hero.body":"Apprenez les soins, la prévention, la vaccination, l'alimentation et la gestion dans une langue claire.","hero.watch":"Voir les leçons","hero.read":"Lire les articles","hero.videos":"Leçons pratiques","hero.farmers":"Éleveurs touchés","hero.new":"Nouveaux conseils",
  "common.explore":"Découvrir","common.viewAll":"Tout voir","common.all":"Tout","common.loading":"Chargement","common.free":"Gratuit","common.comingSoon":"Bientôt disponible",
  "guidance.eyebrow":"Choisissez comment apprendre","guidance.title":"Des connaissances utiles à chaque étape","guidance.videoTitle":"Leçons vidéo sur le terrain","guidance.videoBody":"Suivez des démonstrations sur le logement, l'alimentation, la vaccination et les soins.","guidance.articleTitle":"Explications d'experts","guidance.articleBody":"Comprenez les maladies, les marchés, les risques saisonniers et les bonnes décisions.","guidance.bookTitle":"Bibliothèque agricole","guidance.bookBody":"Lisez des guides gratuits ou débloquez des livres premium en sécurité.",
  "library.eyebrow":"Bibliothèque agricole numérique","library.title":"Des livres pratiques pour mieux élever","library.body":"Trouvez des guides sur la santé, l'alimentation, le logement, la production et la rentabilité.","library.download":"Lire gratuitement","library.soon":"Fichier bientôt disponible","library.empty":"Aucun livre n'est encore disponible.","library.premium":"Premium","library.noCategory":"Aucun livre trouvé dans cette catégorie.","library.howEyebrow":"Comment fonctionne l'accès","library.howTitle":"Commencez gratuitement. Débloquez plus selon vos besoins.","library.howBody":"Chaque livre indique clairement s'il est gratuit ou payant.","library.freeTitle":"Livres gratuits","library.freeBody":"Ouvrez les livres publiés pour les éleveurs sans paiement.","library.premiumTitle":"Livres premium","library.premiumBody":"Payez par un moyen approuvé; après vérification, l'accès est ajouté à votre compte.","library.accountTitle":"Votre compte d'apprentissage","library.accountBody":"Conservez vos achats vérifiés, vos accès et votre futur historique.","library.createAccount":"Créer un compte",
  "videos.eyebrow":"Regardez et appliquez","videos.title":"Leçons avicoles sur le terrain","videos.body":"Regardez des démonstrations pratiques sur tout appareil et appliquez-les à votre ferme.","videos.empty":"Aucune vidéo disponible.","videos.noCategory":"Aucune vidéo trouvée dans cette catégorie.","videos.visit":"Visiter notre chaîne YouTube",
  "blog.eyebrow":"L'élevage expliqué clairement","blog.title":"Des conseils pour de meilleures décisions","blog.body":"Lisez des conseils sur la santé, la planification, les coûts et la gestion avicole.","blog.read":"Lire l'article","blog.back":"Retour aux articles","blog.empty":"Aucun article disponible.","blog.noCategory":"Aucun article trouvé dans cette catégorie.","blog.by":"Par",
  "story.eyebrow":"Conçu pour les éleveurs d'Afrique de l'Est","story.title":"La science vétérinaire rendue pratique.","story.body":"Nous relions l'expertise aux décisions qui rendent les fermes productives, durables et rentables.","story.health":"Prévention des maladies","story.feed":"Alimentation économique","story.business":"Rentabilité agricole",
  "market.eyebrow":"La prochaine étape","market.title":"Des produits avicoles fiables, près de votre ferme.","market.body":"Nous préparons une place de marché où découvrir des médicaments et fournitures vérifiés, comprendre leur usage et commander en ligne.","market.badge":"Marché des médicaments bientôt disponible","market.verify":"Produits vérifiés","market.guidance":"Conseils d'utilisation clairs","market.secure":"Paiement sécurisé par compte",
  "cta.title":"Voyez chaque leçon en pratique.","cta.body":"Suivez les démonstrations, la vaccination et les formations sur notre chaîne YouTube.","cta.visit":"Voir YouTube",
  "about.eyebrow":"À propos d'Isoko y'Ubworozi","about.title":"Le savoir qui transforme les soins en activité durable.","about.body":"Nous transformons la science vétérinaire en étapes pratiques pour les éleveurs, entrepreneurs et jeunes ruraux.","about.missionEyebrow":"Notre mission","about.missionTitle":"Rendre le savoir agricole fiable, compréhensible et utile.","about.missionBody1":"Nous rapprochons la science des décisions quotidiennes: production, prévention, vaccination, alimentation économique et risques financiers.","about.missionBody2":"Le kinyarwanda, complété par l'anglais et le français, permet à chacun d'apprendre à son rythme.","about.statLessons":"Leçons pratiques","about.statFarmers":"Éleveurs touchés","about.statLanguages":"Langues disponibles","about.statUpdates":"Nouveaux conseils","about.valuesEyebrow":"Ce qui nous guide","about.valuesTitle":"Conçu autour des besoins réels","about.valueEducation":"Éducation accessible","about.valueEducationBody":"Des instructions claires dans les langues des éleveurs.","about.valueEvidence":"Preuves pratiques","about.valueEvidenceBody":"Des conseils fondés sur la santé animale.","about.valueSustainability":"Croissance durable","about.valueSustainabilityBody":"Moins de coûts, des animaux sains et des entreprises solides.","about.ctaTitle":"Prêt à améliorer votre ferme ?","about.ctaBody":"Commencez par une leçon gratuite ou explorez la bibliothèque.","about.ctaVideo":"Voir les leçons","about.ctaLibrary":"Explorer la bibliothèque",
  "faq.eyebrow":"Questions fréquentes","faq.title":"Comprendre la plateforme avant de commencer","faq.q1":"Que puis-je apprendre ici ?","faq.a1":"Apprenez l'installation, le logement, l'alimentation, la prévention, la vaccination, les finances et la gestion avec vidéos, articles et livres.","faq.q2":"Comment fonctionnent les livres gratuits ?","faq.a2":"Un livre marqué Gratuit s'ouvre sans paiement et est publié par l'administration pour les éleveurs.","faq.q3":"Comment accéder à un livre premium ?","faq.a3":"Payez par un moyen approuvé. Après vérification, l'accès est associé à votre compte.","faq.q4":"Pourquoi créer un compte ?","faq.a4":"Le compte protège vos achats et servira à suivre l'apprentissage et les commandes.","faq.q5":"Puis-je acheter des médicaments maintenant ?","faq.a5":"Pas encore. Une place de marché vérifiée est en préparation et son ouverture sera annoncée.",
  "contact.eyebrow":"Contacter l'équipe","contact.title":"Posez une question, collaborez ou demandez conseil","contact.body":"Contactez-nous pour l'éducation agricole, les ressources, les partenariats ou l'assistance.","contact.reach":"Coordonnées","contact.location":"Adresse","contact.follow":"Suivre Isoko y'Ubworozi","contact.formTitle":"Envoyer un message","contact.formBody":"Remplissez le formulaire et notre équipe répondra rapidement.","contact.name":"Nom complet","contact.namePlaceholder":"Entrez votre nom complet","contact.email":"Adresse e-mail","contact.subject":"Sujet","contact.subjectPlaceholder":"Comment pouvons-nous vous aider ?","contact.message":"Message","contact.messagePlaceholder":"Expliquez votre demande","contact.send":"Envoyer le message","contact.sent":"Votre message a été reçu. Nous répondrons bientôt.",
  "account.eyebrow":"Votre compte Isoko","account.title":"Regroupez apprentissage et achats dans un espace sécurisé.","account.body":"Inscrivez-vous ou connectez-vous pour l'accès premium et le futur suivi des commandes.","account.login":"Se connecter","account.register":"Créer un compte","account.name":"Nom complet","account.email":"Adresse e-mail","account.password":"Mot de passe","account.submitLogin":"Se connecter en sécurité","account.submitRegister":"Créer mon compte","account.loading":"Veuillez patienter…","account.success":"Vous êtes connecté.","account.logout":"Se déconnecter","account.member":"Compte prêt","account.future":"Vos achats et commandes apparaîtront ici au lancement de ces services.","account.error":"Impossible de terminer la demande. Vérifiez vos informations.","account.switchRegister":"Nouveau ici ? Créer un compte","account.switchLogin":"Déjà inscrit ? Se connecter",
  "privacy.eyebrow":"Vos informations","privacy.title":"Politique de confidentialité","privacy.intro":"Cette politique explique les informations collectées, leur utilisation et vos choix.","privacy.updated":"Dernière mise à jour : 9 septembre 2026","privacy.s1":"Informations collectées","privacy.p1":"Les comptes peuvent collecter nom, e-mail et données nécessaires aux accès payants. Des données techniques peuvent protéger le service.","privacy.s2":"Utilisation des informations","privacy.p2":"Elles servent aux comptes, aux accès, au support, à l'amélioration et à la prévention des abus. Nous ne vendons pas les données personnelles.","privacy.s3":"Paiements et sécurité","privacy.p3":"Les prestataires traitent les paiements selon leurs règles. Nous conservons uniquement les références nécessaires.","privacy.s4":"Vos choix","privacy.p4":"Vous pouvez demander accès, correction ou suppression. Certains registres peuvent être conservés pour des besoins légaux ou comptables.","privacy.s5":"Contact","privacy.p5":"Écrivez à info@isokoyubworozi.rw pour toute question.",
  "terms.eyebrow":"Règles de la plateforme","terms.title":"Conditions d'utilisation","terms.intro":"Ces conditions expliquent l'utilisation responsable des leçons, comptes et ressources.","terms.updated":"Dernière mise à jour : 9 septembre 2026","terms.s1":"Objectif éducatif","terms.p1":"Notre contenu est éducatif et ne remplace pas le diagnostic ou traitement d'un vétérinaire qualifié.","terms.s2":"Comptes","terms.p2":"Fournissez des informations exactes et protégez vos identifiants. Ne partagez pas les accès payants.","terms.s3":"Ressources gratuites et premium","terms.p3":"Les ressources gratuites ne demandent aucun paiement. Les ressources premium exigent paiement et vérification.","terms.s4":"Utilisation du contenu","terms.p4":"Les livres, vidéos, articles et marques sont protégés. L'apprentissage personnel est permis; la revente non autorisée ne l'est pas.","terms.s5":"Modifications et assistance","terms.p5":"Les fonctionnalités peuvent évoluer. Les changements importants seront publiés ici. Contactez-nous pour toute précision.",
  "footer.body":"Nous aidons les éleveurs à bâtir des fermes saines et productives dans leur langue.","footer.links":"Liens rapides","footer.resources":"Ressources","footer.updates":"Restez informé","footer.updateBody":"Recevez nos conseils.","footer.email":"Adresse e-mail","footer.rights":"Tous droits réservés.","footer.privacy":"Confidentialité","footer.terms":"Conditions","footer.vet":"Conseils vétérinaires","footer.vaccine":"Plans de vaccination","footer.feed":"Efficacité alimentaire","footer.finance":"Finances agricoles","footer.payments":"Moyens de paiement prévus","footer.paymentBody":"Ces options serviront aux ressources premium lors du lancement.","footer.paymentSecure":"Le traitement sécurisé sera activé au lancement."
};

const copy = { en, rw, fr };
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: Key) => string };
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("rw");
  useEffect(() => { const stored = localStorage.getItem("isoko-locale") as Locale | null; if (stored && stored in copy) requestAnimationFrame(() => setLocaleState(stored)); }, []);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const setLocale = (next: Locale) => { setLocaleState(next); localStorage.setItem("isoko-locale", next); };
  const value = useMemo(() => ({ locale, setLocale, t: (key: Key) => copy[locale][key] }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}
