"use client";
import { useEffect } from 'react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Link from '@tiptap/extension-link';
import Image from '@tiptap/extension-image';
import Placeholder from '@tiptap/extension-placeholder';
import { FiBold, FiItalic, FiLink, FiList, FiType } from 'react-icons/fi';
export default function RichTextEditor({value,onChange,onRequestImage}:{value:string;onChange:(html:string)=>void;onRequestImage:()=>void}){const editor=useEditor({immediatelyRender:false,extensions:[StarterKit,Link.configure({openOnClick:false}),Image,Placeholder.configure({placeholder:'Write practical, step-by-step guidance…'})],content:value,onUpdate:({editor})=>onChange(editor.getHTML())});useEffect(()=>{if(editor&&value!==editor.getHTML())editor.commands.setContent(value)},[editor,value]);if(!editor)return <div className="h-[500px] animate-pulse rounded-2xl bg-mist"/>;const tool=(active:boolean)=>`grid h-9 w-9 place-items-center rounded-lg transition ${active?'bg-forest text-white':'text-slate hover:bg-mist'}`;return <div className="overflow-hidden rounded-2xl border border-ink/10 bg-white"><div className="flex flex-wrap items-center gap-1 border-b border-ink/8 p-2"><button type="button" aria-label="Bold" className={tool(editor.isActive('bold'))} onClick={()=>editor.chain().focus().toggleBold().run()}><FiBold/></button><button type="button" aria-label="Italic" className={tool(editor.isActive('italic'))} onClick={()=>editor.chain().focus().toggleItalic().run()}><FiItalic/></button><button type="button" aria-label="Heading" className={tool(editor.isActive('heading',{level:2}))} onClick={()=>editor.chain().focus().toggleHeading({level:2}).run()}><FiType/></button><button type="button" aria-label="Bullet list" className={tool(editor.isActive('bulletList'))} onClick={()=>editor.chain().focus().toggleBulletList().run()}><FiList/></button><button type="button" aria-label="Add link" className={tool(editor.isActive('link'))} onClick={()=>{const href=window.prompt('Paste an HTTPS link');if(href)editor.chain().focus().extendMarkRange('link').setLink({href}).run()}}><FiLink/></button><button type="button" onClick={onRequestImage} className="ml-auto rounded-lg px-3 py-2 text-xs font-extrabold text-leaf">+ Media</button></div><EditorContent editor={editor}/><div className="border-t border-ink/8 px-4 py-2 text-[10px] text-slate">Tip: use headings, short paragraphs and lists so farmers can scan instructions quickly.</div></div>}
